### ISSUE TITLE
VS2022 can build BUT getting errors in many places

### ISSUE THREAD

**Issue by GeorgeS2019** [sps014/BlazorBindGen#11] opened 2022-08-27 20:13 UTC
![image](https://user-images.githubusercontent.com/49812372/187046561-06812e5c-10bf-406c-9fd0-a33e9e9db6a1.png)

**Comment by GeorgeS2019** [comment] 2022-08-27 20:16
![image](https://user-images.githubusercontent.com/49812372/187046605-7f411b32-584b-4cf7-a225-6fd8c049d84f.png)

Error CS0117

**Comment by sps014** [comment] 2022-08-27 20:26
Yeah These are source generator errors and I was experimenting one idea to automatically generate binding code from struct, class or record definition .
New proposed experiment (works on wasm): https://github.com/sps014/BlazorBindGen/blob/main/SampleApp/JSBinding/ML5Binding.cs
Old Code
https://github.com/sps014/BlazorBindGen/blob/c881152369ee24b9b5c827473bdaf265769c269a/SampleApp/Pages/ML5Page.razor

**Comment by GeorgeS2019** [comment] 2022-08-27 20:31
I am using the proposed experiment which works on WASM.
Question
Any suggestions on how to switch off these errors which do not prevent one from compiling successfully?

**Comment by sps014** [comment] 2022-08-27 20:33
Can you post error Message ?

**Comment by GeorgeS2019** [comment] 2022-08-27 20:35
![devenv_uhbpHa9RlB](https://user-images.githubusercontent.com/49812372/187047086-0acaeb22-d5f7-4b5e-bd8e-6c22fe22bd46.gif)

**Comment by sps014** [comment] 2022-08-27 20:35
These errors can be caused by poor tooling of Source Generator at this moment, also at this point new API is in development I need  to do lot of code refactoring this month.

**Comment by GeorgeS2019** [comment] 2022-08-27 20:36
![devenv_lMhOxCY4e7](https://user-images.githubusercontent.com/49812372/187047119-fabc7c1b-2fb1-42c9-9d92-b7ea6c633896.gif)

**Comment by GeorgeS2019** [comment] 2022-08-27 20:38
> These errors can be caused by poor tooling of Source Generator at this moment, also at this point new API is in development I need to do lot of code refactoring next month.

For users, it is unclear how stable is the new API. Would you consider separating the new API as a SEPARATE BRANCH which you could merge to master ONCE the code refactoring is done?

**Comment by sps014** [comment] 2022-08-27 20:41
> For users, it is unclear how stable is the new API. Would you consider separating the new API as a SEPARATE BRANCH which you could merge to master ONCE the code refactoring is done?

Yeah that would be better, will create a separate branch.

Also there is workaround for Visual Studio errors(not testesd) https://github.com/dotnet/roslyn/issues/44093

**Comment by GeorgeS2019** [comment] 2022-08-27 20:56
> Yeah that would be better, will create a separate branch.

What you experiment has a consequence on your user.  With more capabilities come more responsibility. :-)

**Comment by sps014** [comment] 2022-09-08 09:42
Closing this as these bugs will be fixed by Visual Studio team in upcoming versions.

**Closed by sps014** 2022-09-08 09:42 UTC
